services:
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "8080:80"

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"